### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by robjbrain** [syropian/vue-input-autowidth#11]
It doesn't seem to work? Do you have a working demo somewhere other than the gif?

https://jsfiddle.net/1Lrgmu7n/

**Comment by syropian** [comment]
In your you set your `v-model` to a `name` property, but in your Vue instance you called it `message`. Make them the same, and it works fine 😄

**Comment by robjbrain** [comment]
the `message` was just left there from the original hello world vuejs example.

I can see now that the actual problem was that I had not defined "name" in my data object.

It's a little annoying that it requires v-model, does it not just work on @input or @change ?
