### ISSUE TITLE
Maybe too narrow on Firefox

### ISSUE THREAD

**Issue by lucaboesch** [syropian/vue-input-autowidth#15]
It could be this needs some inquiry but I think on Firefox (68.0.2 MacOS) the fiels are too narrow.
Other browser do work fine.

<img width="875" alt="grafik" src="https://user-images.githubusercontent.com/377279/63212040-8f9aef80-c0ff-11e9-87f1-7a58547558ae.png">

**Comment by syropian** [comment]
Thanks for the report! I'll try and have a look this week.

**Comment by syropian** [comment]
Hi! This should be fixed in c36118e - released as v1.0.6
