### ISSUE TITLE
Release problem

### ISSUE THREAD

**Issue by usb248** [syropian/vue-input-autowidth#17]
I waiting 1.0.8, but the fix for FF is not here : 
See : https://unpkg.com/vue-input-autowidth@1.0.8/dist/index.umd.min.js whereas : https://github.com/syropian/vue-input-autowidth/commit/dd9c3d90006a30a52af7c68e997a0950fa58bdc8#diff-86ae3ce16deeb1cf5903641a8f921997R25

Please fix

**Comment by syropian** [comment]
Whoops, somehow the dist files didn't get checked in. Try 1.0.9, it works for me. https://unpkg.com/vue-input-autowidth@1.0.9/dist/index.umd.min.js
