### ISSUE TITLE
q is not defined

### ISSUE THREAD

**Issue by ducdev** [syropian/vue-input-autowidth#2]
![image](https://user-images.githubusercontent.com/3524016/30363742-8508a830-988b-11e7-9f79-0f3c7fc6c7ca.png)
I got this error on production (Heroku), I've been using Vue 2 with Meteor.

**Comment by ducdev** [comment]
I would say I is working well on localhost.

**Comment by syropian** [comment]
There should be no difference on localhost vs a Heroku instance. Any reproduction steps? I don't personally use Meteor or Heroku.
