### ISSUE TITLE
Paste text breaks max width

### ISSUE THREAD

**Issue by davidhernandeze** [syropian/vue-input-autowidth#21]

**Comment by davidhernandeze** [comment]
When I use percentages on maxWidth and copy text until the inputs is full, if a continue pasting text the input start growing more than the maxWidth

**Comment by syropian** [comment]
Thanks for the report, could you please include an example reproducing the issue in something like CodeSandbox, CodePen, JSFiddle, etc? Cheers.

**Comment by mhmdmar** [comment]
I confirm with @davidhernandeze I have the same issue, on paste event the component doesn't respect the maxWidth for some reason and expands according to the text

**Comment by mhmdmar** [comment]
@syropian I updated to the latest version and couldn't reproduce the bug, I think this should be  closed 👍
