### ISSUE TITLE
Not working when using :value directive on input.

### ISSUE THREAD

**Issue by janhaa** [syropian/vue-input-autowidth#22]
I'm currently injecting data into the input component directly via the :value directive, which does not trigger the autoresize. Changing to v-model fixes it.

Is there a fundamental restriction when using the value directive which makes the autoresize functionality not work?

**Comment by syropian** [comment]
Thanks for the report, I'll go ahead and try and reproduce the problem and get back to you.

**Comment by syropian** [comment]
I was able to reproduce the issue, and I'll have a fix out shortly. Thanks again1

**Comment by syropian** [comment]
@janhaa Should be fixed in the latest version (1.0.10). Cheers!
