### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by maxiloc** [syropian/vue-input-autowidth#28]
I am currently migrating some of my apps to Vue3 which is currently in RC-2.

There is a few breaking changes to the directive API making the library not compatible.

I found a workaround in my apps by doing:

```js
import VueInputAutowidth from 'vue-input-autowidth';

export default {
  [...]
  directives: {
    autowidth: {
      beforeMount: VueInputAutowidth.bind,
      mounted: VueInputAutowidth.inserted,
      updated: VueInputAutowidth.componentUpdated,
      unmounted: VueInputAutowidth.unbind,
    },
  },
}
```

but it would be nice to add support.

**Comment by vadimszzz** [comment]
Vue 3 doesn't work.

**Comment by syropian** [comment]
I'm on vacation this week, but I will definitely look into this when I'm back.

**Comment by vadimszzz** [comment]
Ok thx

**Comment by syropian** [comment]
Hi all, I'm still finishing up tests and docs, but you can try out the Vue 3 version by installing the `next` tag

```bash
npm install --save vue-input-autowidth@next
# or...
yarn add vue-input-autowidth@next
```

Please note there's one small breaking change: The `comfortZone` option should now be a string that is any valid "size" value in CSS. Eg `10px`, `4rem`, `2ch`, etc.

All the code, and docs-in-progress live on the [v2](https://github.com/syropian/vue-input-autowidth/tree/v2) branch if you'd like to check it out.

**Comment by vadimszzz** [comment]
Thx
