### ISSUE TITLE
Flicker on keydown in Chrome/Safari

### ISSUE THREAD

**Issue by sdnyco** [syropian/vue-input-autowidth#3]
I've been testing vue-input-autowidth and it seems there is a slight flicker on keydown in Chrome/Safari (Version 61.0.3163.100) but **not** in Firefox.

All extensions were disabled.

[Loom Recording](https://www.useloom.com/share/0b82e01b58c644aeba5a0d4704f1ad25)

**Comment by syropian** [comment]
Thanks for the report! Do you have `box-sizing: border-box;` on that element's css? I'm unable to reproduce in the example. Could you copy your example to a JSFiddle or similar?

**Comment by sdnyco** [comment]
It's really bizarre. My example is a little too complex to post on jsbin.

When I build a simple input component in jsbin it works fine (unless I add `letter-spacing`).
When I remove all of the styles of my app's component it still flickers.

Even when I remove:

``` css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

**Comment by sdnyco** [comment]
Addition: On an old project, with no problems whatsoever, I just update `vue`, `vue-loader` and `vue-template-compiler`–and then it broke.

**Comment by syropian** [comment]
Very strange! Almost makes me think it's something funny with Vue's re-rendering code. I'll spend a bit of time seeing if I can reproduce.

**Comment by sdnyco** [comment]
Various things seem to exacerbate the problem. With my [CodePen](https://codepen.io/anon/pen/LOVmjB) I have so far identified `letter-spacing`, `font-size` and `box-sizing` as potential factors.

I was using `2.5.2` of Vue.

**Comment by syropian** [comment]
It's a bit surprising letter-spacing affects it, as I do [copy letter-spacing to the clone helper](https://github.com/syropian/vue-input-autowidth/blob/master/src/vue-input-autowidth.js#L33). I have not checked compatibility with the latest version of Vue, so I'll have to do that.

**Comment by anthdm** [comment]
We had the exact same issue and fixed it.

1. box-sizing needs to be initial (default)
2. You need the comfort zone to be around 25 (for smoothness)
3. You need that comfort zone to apply before and after the text. (left and right)
=> Set the text align to center to achieve this.

**Comment by sdnyco** [comment]
I played with the [pen](https://codepen.io/anon/pen/LOVmjB) I posted above, and changing `box-sizing` and `text-align: center` had no impact whatsoever.

Only increasing the `comfortZone` to `25` seemed to smoothen things.

**Comment by syropian** [comment]
Thanks for investigating guys, I'm going to play around with it today and see if I can come up with anything.

**Comment by m4tty-d** [comment]
@syropian I still experience this issue in Chrome. Have you come up with a solution?
Setting the `comfortZone` to something bigger than `20` seems to do the trick, but it doesn't really look good.

**Comment by lmgonzalves** [comment]
Similar issue here. Tried the workarounds but still having some small flickering.

**Comment by eNzyOfficial** [comment]
Same problem, adding comfort zone 20+ fixes it but this is a little too high for me unfortunately

**Comment by syropian** [comment]
I tried in the latest version of Chrome and I wasn't seeing this anymore with the latest version.
