### ISSUE TITLE
Wrong width on Input with type number

### ISSUE THREAD

**Issue by einlichtvogel** [syropian/vue-input-autowidth#66]
![Bildschirm­foto 2023-04-02 um 17 38 06](https://user-images.githubusercontent.com/65811753/229363402-cfddd2d8-3ebd-4a7a-9fa3-68fcb87c2d38.png)

**Comment by syropian** [comment]
Does passing a custom `comfortZone` value help?

```vue
<input
    type="text"
    v-model="msg"
    v-autowidth="{
      comfortZone: '20px', // adjust this to fit your needs
    }"
  />
```

**Comment by einlichtvogel** [comment]
No, sadly doesn't work!

**Comment by syropian** [comment]
You should be able to use a combination of the `minWidth` and `comfortZone` options to achieve what you need. You can see an example here — https://stackblitz.com/edit/vue-hyxw37?file=src/App.vue

Let me know if that's enough to solve issue!

**Comment by einlichtvogel** [comment]
That solved it, yes!
Thank you :)
