### ISSUE TITLE
Not working when trying to use it with Nuxt3.

### ISSUE THREAD

**Issue by Don404** [syropian/vue-input-autowidth#67]
It shows me an error:

500
Cannot read properties of undefined (reading 'getSSRProps')

**Comment by syropian** [comment]
You'll probably want to either wrap your input in a `<ClientOnly>` tag or wrap the library in a small client-only Nuxt plugin. Let me know if that works!

**Comment by Don404** [comment]
Sorry for the late reply. When I wrap it in `<ClientOnly>` tag the error is fixed. But now it has the following warning: `Failed to resolve directive: autowidth`
